language: android
dist: trusty
jdk: oraclejdk8
env:
  global:
    - GRADLE_OPTS="-Xmx3072m"
    - ADB_INSTALL_TIMEOUT=10
  matrix:
    - ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
branches:
  only:
    - develop
    - master

stages:
  - compile
  - test
  - name: deploy
    if: type = push AND branch = develop

cache:
  directories:
    - $HOME/.android/build-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
install:
  - sdkmanager tools
  - sdkmanager emulator
  - sdkmanager "system-images;$ANDROID_TARGET;default;$ANDROID_ABI"
  - echo no | avdmanager create avd --force -n test -k "system-images;$ANDROID_TARGET;default;$ANDROID_ABI"
  - ./gradlew connectedCheck --continue --stacktrace --parallel

jobs:
  fast_finish: true
  include:
    - name: "Build Debug"
      stage: compile
      install: skip
      script: ./gradlew clean assembleDebug --continue --stacktrace --parallel

    - name: "Build Release"
      stage: test
      install: skip
      script: ./gradlew clean assembleRelease --continue --stacktrace --parallel

    - name: "Static Analysis"
      stage: compile
      install: skip
      script: ./gradlew check --continue --stacktrace --parallel
      after_failure:
        - cat /home/travis/build/gyasistory/Gyasi-Story-App/build/reports/lint-results*.xml
        - cat /home/travis/build/gyasistory/Gyasi-Story-App/*/build/reports/lint-results*.xml

    - name: "Release Beta"
      stage: deploy
      install:
        - git fetch --unshallow
      script:
        # Add Beta Release Platform
        - ./gradlew clean assembleDebug appDistributionUploadDebug

notifications:
  email: true
